version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Monta la cartella di lavoro nel container
      - /app/node_modules  # Evita problemi con node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Abilita il polling per il watcher
      - NEXT_PUBLIC_ENV=development  # Imposta la variabile d'ambiente per Next.js
